apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: ranfa23/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - infra/k8s/*
deploy:
  kubectl: {}
